In [2]:
1+1

2

In [42]:
import numpy as np
import torch

/opt/homebrew/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [30]:
parts = np.array(
    [
        [0, [1, 299]], 
        [1, [300, 400]],
        [2, [500, 600]],
    ],
    dtype=object,
)
print(parts)
print(parts.shape)

[[0 list([1, 299])]
 [1 list([300, 400])]
 [2 list([500, 600])]]
(3, 2)


In [29]:
np.append(parts, [[3, [1,2]]], axis=0)

array([[0, list([1, 299])],
       [1, list([300, 400])],
       [2, list([500, 600])],
       [3, list([1, 2])]], dtype=object)

In [5]:
parts.shape

(3, 2)

In [6]:
interval_parts = parts[:,1:]
interval_parts

array([[list([1, 299])],
       [list([300, 400])],
       [list([500, 600])]], dtype=object)

In [45]:
tensor = torch.tensor(interval_parts.tolist())
tensor

tensor([[[  1, 299]],

        [[300, 400]],

        [[500, 600]]])

In [50]:
tensor.flatten()

tensor([  1, 299, 300, 400, 500, 600])

In [46]:
tensor.numpy()

array([[[  1, 299]],

       [[300, 400]],

       [[500, 600]]])

In [73]:
new_interval_parts = np.array([], dtype=object)

for part in interval_parts:
    new_interval_parts = np.append(new_interval_parts, np.array(part, dtype=object))

print(new_interval_parts)
print(new_interval_parts.shape)

[list([1, 299]) list([300, 400]) list([500, 600])]
(3,)


In [89]:
len(new_interval_parts)

3

In [90]:
new_interval_parts = new_interval_parts.reshape((len(new_interval_parts),1))

In [91]:
print(parts[:,:1])
print(parts[:,:1].shape)

[[0]
 [1]
 [2]]
(3, 1)


In [93]:
print(parts[:,:1].shape)
print(new_interval_parts.shape)

np.concatenate([parts[:,:1], new_interval_parts], axis=1)

(3, 1)
(3, 1)


array([[0, list([1, 299])],
       [1, list([300, 400])],
       [2, list([500, 600])]], dtype=object)

In [56]:
np.array([[1,2], [3,4]], dtype=object).flatten()

array([1, 2, 3, 4], dtype=object)

In [57]:
np.array([1, [3,4]], dtype=object).flatten()

array([1, list([3, 4])], dtype=object)

In [65]:
class Hi:
    def hi(self, a):
        print(a)
    def hi(self, a, b):
        print(a+b)
h = Hi()

In [67]:
h.hi(1, 2)

3
